[files]
extend-exclude = [
  "crates/oxc_parser/src/lexer/byte_handlers.rs",
  "crates/ssc_parser/src/lexer/byte_handlers.rs",
  "crates/ssc_css_parser/src/lexer/byte_handler.rs",
  "crates/oxc_parser/CHANGELOG.md"
]

[default.extend-words]
trivias = "trivias"
